name: Shared Tests

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'
          cache-dependency-path: |
            shared/package-lock.json
            web/package-lock.json
            functions/package-lock.json

      - name: Install shared dependencies
        working-directory: shared
        run: npm ci

      - name: Build shared package
        working-directory: shared
        run: npm run build

      - name: Install dependencies
        working-directory: web
        run: npm ci

      - name: Run tests
        working-directory: web
        run: npm test

      - name: Install Cloud Run function dependencies
        working-directory: functions
        run: npm ci

      - name: Run Cloud Run function tests
        working-directory: functions
        run: npm test
